config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    resources :microposts
    resources :users
    resources :account_activations, only: :edit
    root to: 'static_pages#home'
    get 'static_pages/help'
    get 'password_resets/new'
    get 'password_resets/edit'
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    resources :users, only: %i(new create)
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/account_activations", to: "account_activations#edit"
    resources :password_resets, only: [:new, :create, :edit, :update]
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path , id: "logo" %>
    <nav class="dropdown">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("home"), root_path %></li>
        <li><%= link_to t("help"), static_pages_help_path %></li>
        <li><%= link_to t("users"), users_path %></li>
        <% if logged_in? %>
        <li><%= link_to current_user.name %>
          <ul class="pop">
            <li><%= link_to t("profile"), current_user %></li>
            <li><%= link_to t("setting"), edit_user_path(current_user) %></li>
            <li><%= link_to t("logout"), logout_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to t("login"), login_path %></li>
        <% end %>
        <li style="margin-top: 14px; margin-left: 7px" ><%= t("language")%>
          <ul class="pop" >
            <li><%= link_to t("english"), locale:"en" %></li>
            <li><%= link_to t("viet"), locale:"vi" %></li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title yield :title %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>